name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t vulnerablelightapp .
      
    - name: Run Docker container
      run: docker run -d -p 3000:3000 vulnerablelightapp

    - name: Wait for the container to be ready
      run: sleep 10

    - name: Test the application
      run: curl -k https://127.0.0.1:3000
